<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>XivWayfinder</AssemblyName>
    <RootNamespace>XivWayfinder.Plugin</RootNamespace>
    <Version>0.1.0.2</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XivWayfinder.Core\XivWayfinder.Core.csproj" />
    <Compile Include="..\Shared\IpcContract.cs" Link="Shared\IpcContract.cs" />
  </ItemGroup>
</Project>
