#!/usr/bin/env python3
"""Render CHANGELOG.md from changelog.json, the changelog for Wayfinder.

changelog.json is the single source of truth: release notes and the installer's
changelog are written from it, and CHANGELOG.md is generated from it so they can never
disagree.

    tools/changelog.py            write CHANGELOG.md
    tools/changelog.py --check    exit 1 (and print a diff) if it is out of date
    tools/changelog.py --dump     the sections as JSON (tools/releasekit.py reads this)
    tools/changelog.py --release X.Y.Z --date YYYY-MM-DD [--title TITLE]
                                  turn the unreleased section into release X.Y.Z;
                                  tools/release.sh does this, nobody needs to by hand

Statuses mean the same thing in every one of these mods:

    new   NEW    in a release, seen working in game
    fix   FIX    in a release, seen working in game
    beta  BETA   merged, but not yet verified in game
    next  SOON   still being built

Nothing here needs a toolchain: python3 only, so CI can answer in seconds.
"""

import argparse
import difflib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "changelog.json")
TARGET = os.path.join(ROOT, "CHANGELOG.md")

TAGS = {
    "new": ("NEW", "Added"),
    "fix": ("FIX", "Fixed"),
    "beta": ("BETA", "Merged, not yet verified in game"),
    "next": ("SOON", "Being built"),
}

PREAMBLE = """<!-- Generated from changelog.json by tools/changelog.py. Do not edit this file:
     edit changelog.json and run tools/changelog.py. CI fails when they drift. -->

Statuses mean the same thing in every one of these mods:

* **NEW** / **FIX** — in a release, seen working in game.
* **BETA** — merged, but not yet verified in game.
* **SOON** — still being built.
"""


def load():
    with open(SOURCE, encoding="utf-8") as fh:
        data = json.load(fh)
    for rel in data["releases"]:
        for key in ("version", "title", "blurb", "items"):
            if key not in rel:
                raise SystemExit("changelog.json: release %r has no %s" % (rel.get("version"), key))
        if not rel["items"]:
            raise SystemExit("changelog.json: release %s has no items" % rel["version"])
        for item in rel["items"]:
            if item.get("status") not in TAGS:
                raise SystemExit(
                    "changelog.json: unknown status %r in %s" % (item.get("status"), rel["version"])
                )
            if not item.get("text"):
                raise SystemExit("changelog.json: an item in %s has no text" % rel["version"])
    return data


def render(data):
    out = ["# Changelog\n\n%s\n\n%s" % (data["intro"].rstrip(), PREAMBLE)]
    for rel in data["releases"]:
        if rel["version"] == "next":
            out.append("\n## [Unreleased] — %s\n" % rel["title"])
        elif rel.get("date") and rel["date"] not in rel["title"]:
            out.append("\n## [%s] — %s — %s\n" % (rel["version"], rel["date"], rel["title"]))
        else:
            out.append("\n## [%s] — %s\n" % (rel["version"], rel["title"]))
        out.append("\n%s\n" % rel["blurb"])
        groups = []
        for item in rel["items"]:
            if not groups or groups[-1][0] != item["status"]:
                groups.append((item["status"], []))
            groups[-1][1].append(item["text"])
        single = len({i["status"] for i in rel["items"]}) == 1
        for status, texts in groups:
            if not single:
                out.append("\n### %s\n" % TAGS[status][1])
            out.append("\n")
            for text in texts:
                out.append("* %s\n" % text)
    return "".join(out)


RELEASED_BLURB = (
    "BETA entries are in this release but have not been verified in game yet; "
    "they become NEW or FIX once they have been seen working."
)


def release(data, version, date, title):
    """Turn the unreleased section into release `version`.

    Entries still being built ("next") stay behind in the unreleased section; everything
    else moves, status and all."""
    rels = data["releases"]
    at = next((n for n, r in enumerate(rels) if r["version"] == "next"), None)
    if at is None:
        raise SystemExit("changelog.json: no unreleased (next) section to release")
    staying = [i for i in rels[at]["items"] if i["status"] == "next"]
    moving = [i for i in rels[at]["items"] if i["status"] != "next"]
    if not moving:
        raise SystemExit("changelog.json: nothing in the unreleased section is merged yet")
    released = {
        "version": version,
        "title": title or "Released " + date,
        "date": date,
        "blurb": RELEASED_BLURB,
        "items": moving,
    }
    if staying:
        rels[at]["items"] = staying
        rels.insert(at + 1, released)
    else:
        rels[at] = released
    return data


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail when CHANGELOG.md is out of date")
    ap.add_argument("--dump", action="store_true", help="print the sections as JSON")
    ap.add_argument("--release", metavar="X.Y.Z", help="turn the unreleased section into this release")
    ap.add_argument("--date", help="with --release: YYYY-MM-DD")
    ap.add_argument("--title", help="with --release: the release's name")
    args = ap.parse_args()
    if args.dump:
        rels = [dict(r, date=r.get("date")) for r in load()["releases"]]
        json.dump(rels, sys.stdout, indent=1)
        return 0
    if args.release:
        if not args.date:
            raise SystemExit("--release needs --date")
        data = release(load(), args.release, args.date, args.title)
        with open(SOURCE, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print("released %s in changelog.json" % args.release)
        return 0
    wanted = render(load())
    if not args.check:
        with open(TARGET, "w", encoding="utf-8") as fh:
            fh.write(wanted)
        print("wrote %s" % os.path.relpath(TARGET, ROOT))
        return 0
    try:
        with open(TARGET, encoding="utf-8") as fh:
            have = fh.read()
    except FileNotFoundError:
        have = ""
    if have == wanted:
        print("CHANGELOG.md matches changelog.json")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            have.splitlines(True), wanted.splitlines(True),
            "CHANGELOG.md", "changelog.json (rendered)",
        )
    )
    sys.stderr.write("\nCHANGELOG.md is out of date: run tools/changelog.py\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
